export const IconsNames = {
    musicianIcon: "material-symbols:person-rounded",
    albumIcon: "material-symbols:album",
    trackIcon: "material-symbols:music-note-rounded",
    playlistIcon: "material-symbols:playlist-add-rounded",
    likeIcon: "material-symbols:favorite",
    playIcon: "material-symbols:play-arrow",
    dotsIcon: "material-symbols:more-horiz",
    homeIcon: "material-symbols:home-outline-rounded",
    historyIcon: "material-symbols:history-rounded",
    menuIcon: "material-symbols:menu",
    searchIcon: "material-symbols:search",
    loginIcon: "material-symbols:login-rounded",
    logoutIcon: "material-symbols:logout-rounded",
    securityIcon: "material-symbols:security",
    guitarIcon: "mdi:guitar-electric",
};
