export const IconsNames = {
    userIcon: "material-symbols:person-rounded",
    albumIcon: "material-symbols:album",
    trackIcon: "material-symbols:music-note-rounded",
    playlistIcon: "material-symbols:playlist-add-rounded",
    likeIcon: "material-symbols:favorite",
    dislikeIcon: "ion:heart-dislike",
    playIcon: "material-symbols:play-arrow",
    dotsIcon: "material-symbols:more-horiz",
    homeIcon: "material-symbols:home-outline-rounded",
    historyIcon: "material-symbols:history-rounded",
    menuIcon: "material-symbols:menu",
    searchIcon: "material-symbols:search",
    loginIcon: "material-symbols:login-rounded",
    logoutIcon: "material-symbols:logout-rounded",
    securityIcon: "material-symbols:security",
    guitarIcon: "mdi:guitar-electric",
    settingsIcon: "material-symbols:settings",
    pencilIcon: "material-symbols:edit",
    deleteIcon: "material-symbols:delete",
    changeIcon: "material-symbols:change-circle-rounded",
    listIcon: "material-symbols:list",
    plusIcon: "material-symbols:add-rounded",
    imageIcon: "material-symbols:image",
    shareIcon: "material-symbols:share",
    backIcon: "material-symbols:arrow-back",
};
