version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=semolik-music
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abobus
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d semolik-music" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=abobus
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=semolik-music
    ports:
      - '8000:8000'
