from backend.schemas.error import ALBUM_NOT_FOUND, HTTP_401_UNAUTHORIZED, USER_NOT_FOUND, NOT_ENOUGH_RIGHTS_403
from fastapi import status
UNAUTHORIZED_401 = {status.HTTP_401_UNAUTHORIZED: {
    "model": HTTP_401_UNAUTHORIZED}}

NOT_FOUND_USER = {status.HTTP_404_NOT_FOUND: {"model": USER_NOT_FOUND}}
NOT_FOUND_ALBUM = {status.HTTP_404_NOT_FOUND: {"model": ALBUM_NOT_FOUND}}
NOT_ENOUGH_RIGHTS = {status.HTTP_403_FORBIDDEN: {
    "model": NOT_ENOUGH_RIGHTS_403}}
