/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ALBUM_NOT_FOUND } from './models/ALBUM_NOT_FOUND';
export type { AlbumAfterUpload } from './models/AlbumAfterUpload';
export type { AlbumInfo } from './models/AlbumInfo';
export type { AlbumInfoUploaded } from './models/AlbumInfoUploaded';
export type { AlbumInfoWithoutMusician } from './models/AlbumInfoWithoutMusician';
export type { AlbumTrack } from './models/AlbumTrack';
export type { AlbumWithTracks } from './models/AlbumWithTracks';
export type { AlbumWithTracksUploaded } from './models/AlbumWithTracksUploaded';
export type { AllSearchItem } from './models/AllSearchItem';
export type { Body_create_album_api_v1_albums_post } from './models/Body_create_album_api_v1_albums_post';
export type { Body_create_clip_api_v1_clips_post } from './models/Body_create_clip_api_v1_clips_post';
export type { Body_create_genre_api_v1_genres_post } from './models/Body_create_genre_api_v1_genres_post';
export type { Body_create_slide_api_v1_slider_post } from './models/Body_create_slide_api_v1_slider_post';
export type { Body_send_update_role_request_api_v1_roles_change_post } from './models/Body_send_update_role_request_api_v1_roles_change_post';
export type { Body_update_album_api_v1_albums__album_id__put } from './models/Body_update_album_api_v1_albums__album_id__put';
export type { Body_update_clip_api_v1_clips__clip_id__put } from './models/Body_update_clip_api_v1_clips__clip_id__put';
export type { Body_update_genre_api_v1_genres__genre_id__put } from './models/Body_update_genre_api_v1_genres__genre_id__put';
export type { Body_update_slide_api_v1_slider__slide_id__put } from './models/Body_update_slide_api_v1_slider__slide_id__put';
export type { Body_update_track_by_id_api_v1_tracks__track_id__put } from './models/Body_update_track_by_id_api_v1_tracks__track_id__put';
export type { Body_update_user_avatar_api_v1_users_me_avatar_put } from './models/Body_update_user_avatar_api_v1_users_me_avatar_put';
export type { Body_update_user_public_avatar_api_v1_users_me_public_avatar_put } from './models/Body_update_user_public_avatar_api_v1_users_me_public_avatar_put';
export type { Body_upload_track_api_v1_albums__album_id__track_post } from './models/Body_upload_track_api_v1_albums__album_id__track_post';
export type { ChangePassword } from './models/ChangePassword';
export type { ChangeRoleRequestFullInfo } from './models/ChangeRoleRequestFullInfo';
export { ChangeRoleRequestStatus } from './models/ChangeRoleRequestStatus';
export type { CreateAlbumJson } from './models/CreateAlbumJson';
export type { CreateSlide } from './models/CreateSlide';
export type { CreateSupportMessage } from './models/CreateSupportMessage';
export type { File } from './models/File';
export { FilterGenreEnum } from './models/FilterGenreEnum';
export type { Genre } from './models/Genre';
export type { GENRE_IS_NOT_UNIQUE } from './models/GENRE_IS_NOT_UNIQUE';
export type { GENRE_NOT_FOUND } from './models/GENRE_NOT_FOUND';
export type { GenreFullInfo } from './models/GenreFullInfo';
export type { GenreStats } from './models/GenreStats';
export type { HistoryAlbum } from './models/HistoryAlbum';
export type { HistoryItem } from './models/HistoryItem';
export type { HistoryMusician } from './models/HistoryMusician';
export type { HistoryPlaylist } from './models/HistoryPlaylist';
export type { HistoryTrack } from './models/HistoryTrack';
export type { HTTP_401_UNAUTHORIZED } from './models/HTTP_401_UNAUTHORIZED';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { ImageLink } from './models/ImageLink';
export type { LikesInfo } from './models/LikesInfo';
export type { MusicianClip } from './models/MusicianClip';
export type { MusicianClipWithoutMusician } from './models/MusicianClipWithoutMusician';
export type { MusicianClipWithoutTrack } from './models/MusicianClipWithoutTrack';
export type { MusicianContent } from './models/MusicianContent';
export type { MusicianFullInfo } from './models/MusicianFullInfo';
export type { MusicianInfo } from './models/MusicianInfo';
export type { MusicianProfile } from './models/MusicianProfile';
export type { NOT_ENOUGH_RIGHTS_403 } from './models/NOT_ENOUGH_RIGHTS_403';
export { Order } from './models/Order';
export { order_playlist_by } from './models/order_playlist_by';
export { OrderAlbums } from './models/OrderAlbums';
export type { PlaylistBase } from './models/PlaylistBase';
export type { PlaylistCreate } from './models/PlaylistCreate';
export type { PlaylistInfo } from './models/PlaylistInfo';
export type { PlaylistInfoBase } from './models/PlaylistInfoBase';
export type { PlaylistInfoWithoutTracks } from './models/PlaylistInfoWithoutTracks';
export type { PlaylistTrack } from './models/PlaylistTrack';
export type { PublicProfile } from './models/PublicProfile';
export type { PublicProfileLinks } from './models/PublicProfileLinks';
export type { PublicProfileLinksUsernames } from './models/PublicProfileLinksUsernames';
export type { PublicProfileModifiable } from './models/PublicProfileModifiable';
export type { PublicProfileUsernames } from './models/PublicProfileUsernames';
export type { RoleRequestAnswer } from './models/RoleRequestAnswer';
export type { SearchAlbum } from './models/SearchAlbum';
export type { SearchClip } from './models/SearchClip';
export type { SearchMusician } from './models/SearchMusician';
export type { SearchPlaylist } from './models/SearchPlaylist';
export type { SearchTrack } from './models/SearchTrack';
export type { Slide } from './models/Slide';
export type { StatsDay } from './models/StatsDay';
export type { SupportMessageLogin } from './models/SupportMessageLogin';
export { SupportMessageStatus } from './models/SupportMessageStatus';
export { SupportMessageType } from './models/SupportMessageType';
export type { Track } from './models/Track';
export type { TrackAfterUpload } from './models/TrackAfterUpload';
export type { TrackStats } from './models/TrackStats';
export type { TrackWithoutMusician } from './models/TrackWithoutMusician';
export type { UpdateAlbumJson } from './models/UpdateAlbumJson';
export type { UpdateRoleRequestAnswer } from './models/UpdateRoleRequestAnswer';
export type { USER_NOT_FOUND } from './models/USER_NOT_FOUND';
export type { UserAuth } from './models/UserAuth';
export type { UserBase } from './models/UserBase';
export type { UserInfo } from './models/UserInfo';
export type { UserInfoWithPlaylists } from './models/UserInfoWithPlaylists';
export type { UserRegister } from './models/UserRegister';
export type { UsersStats } from './models/UsersStats';
export { UserTypeEnum } from './models/UserTypeEnum';
export type { ValidationError } from './models/ValidationError';

export { Service } from './services/Service';
