"""renamed column length->duration in tracks table

Revision ID: 02fcd9236d96
Revises: b9329f8624d4
Create Date: 2022-11-04 21:19:52.049166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02fcd9236d96'
down_revision = 'b9329f8624d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('duration', sa.DECIMAL(), nullable=False))
    op.drop_column('tracks', 'length')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('length', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('tracks', 'duration')
    # ### end Alembic commands ###
