"""added tracks table

Revision ID: 03ab21e35cc9
Revises: 6e68ccdaf77d
Create Date: 2022-11-04 12:19:45.516664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ab21e35cc9'
down_revision = '6e68ccdaf77d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('feat', sa.String(length=50), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.Column('length', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['public_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
