"""removed filename column in tracks table

Revision ID: 08934a327f78
Revises: af20dd494a89
Create Date: 2022-11-29 00:12:31.158714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08934a327f78'
down_revision = 'af20dd494a89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
