"""updated slider model

Revision ID: 0bf32825db5d
Revises: 2a937e8bda45
Create Date: 2023-03-26 13:14:31.100841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bf32825db5d'
down_revision = '2a937e8bda45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slides', 'active_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('slides', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slides', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('slides', 'active_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
