"""added index=True to Album.name

Revision ID: 118c78146e2c
Revises: 
Create Date: 2023-02-16 19:56:46.807263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118c78146e2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_albums_name'), 'albums', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_albums_name'), table_name='albums')
    # ### end Alembic commands ###
