"""added picture to tracks table

Revision ID: 12a2132c82c4
Revises: 02fcd9236d96
Create Date: 2022-11-04 21:45:36.842615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a2132c82c4'
down_revision = '02fcd9236d96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tracks', 'files', ['picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_column('tracks', 'picture_id')
    # ### end Alembic commands ###
