"""added genres to album

Revision ID: 1810543d2764
Revises: afdd93fb842d
Create Date: 2022-11-11 12:46:26.610558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1810543d2764'
down_revision = 'afdd93fb842d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums_genres_table',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('album_id', 'genre_id')
    )
    op.drop_table('tracks_genres_table')
    op.drop_constraint('albums_genre_id_fkey', 'albums', type_='foreignkey')
    op.drop_column('albums', 'genre_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('albums_genre_id_fkey', 'albums', 'genres', ['genre_id'], ['id'])
    op.create_table('tracks_genres_table',
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='tracks_genres_table_genre_id_fkey'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name='tracks_genres_table_track_id_fkey'),
    sa.PrimaryKeyConstraint('track_id', 'genre_id', name='tracks_genres_table_pkey')
    )
    op.drop_table('albums_genres_table')
    # ### end Alembic commands ###
