"""changed public profile description length

Revision ID: 1e32c82abce2
Revises: 75907183733f
Create Date: 2022-11-26 21:41:29.642259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e32c82abce2'
down_revision = '75907183733f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('public_profiles', 'description',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('public_profiles', 'description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=180),
               existing_nullable=True)
    # ### end Alembic commands ###
