"""updated chage roles

Revision ID: 2a937e8bda45
Revises: 
Create Date: 2023-03-20 17:52:09.919931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a937e8bda45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers_change_role_requests', sa.Column('accepted', sa.Boolean(), nullable=True))
    op.drop_column('answers_change_role_requests', 'setted_account_status')
    op.drop_column('change_role_requests', 'requested_account_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_role_requests', sa.Column('requested_account_status', postgresql.ENUM('musician', 'user', 'superuser', name='usertypeenum'), autoincrement=False, nullable=False))
    op.add_column('answers_change_role_requests', sa.Column('setted_account_status', postgresql.ENUM('musician', 'user', 'superuser', name='usertypeenum'), autoincrement=False, nullable=False))
    op.drop_column('answers_change_role_requests', 'accepted')
    # ### end Alembic commands ###
