"""create table change_role_requests_files

Revision ID: 2e9f7155d847
Revises: 94c3d767ac69
Create Date: 2022-11-28 22:28:54.583748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e9f7155d847'
down_revision = '94c3d767ac69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_role_requests_files',
    sa.Column('change_role_request_id', sa.Integer(), nullable=False),
    sa.Column('file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['change_role_request_id'], ['change_role_requests.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('change_role_request_id', 'file_id')
    )
    op.drop_column('change_role_requests', 'files_ids')
    op.drop_constraint('public_profiles_picture_id_fkey', 'public_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'public_profiles', 'images', ['picture_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('users_picture_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'images', ['picture_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_picture_id_fkey', 'users', 'images', ['picture_id'], ['id'])
    op.drop_constraint(None, 'public_profiles', type_='foreignkey')
    op.create_foreign_key('public_profiles_picture_id_fkey', 'public_profiles', 'images', ['picture_id'], ['id'])
    op.add_column('change_role_requests', sa.Column('files_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_table('change_role_requests_files')
    # ### end Alembic commands ###
