"""added cascade delete

Revision ID: 39e6b852a44d
Revises: 1810543d2764
Create Date: 2022-11-12 21:23:20.794492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e6b852a44d'
down_revision = '1810543d2764'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
