"""add_picture_id

Revision ID: 49766419e3c0
Revises: dfb2695d0de7
Create Date: 2022-10-27 13:58:59.841110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49766419e3c0'
down_revision = 'dfb2695d0de7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_profiles_links', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'public_profiles_links', 'files', ['picture_id'], ['id'])
    op.add_column('users', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'files', ['picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'picture_id')
    op.drop_constraint(None, 'public_profiles_links', type_='foreignkey')
    op.drop_column('public_profiles_links', 'picture_id')
    # ### end Alembic commands ###
