"""delete tracks set null to clip

Revision ID: 55f53ebb4a6c
Revises: ef0245637bc0
Create Date: 2023-05-06 15:20:52.399628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f53ebb4a6c'
down_revision = 'ef0245637bc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clips_track_id_fkey', 'clips', type_='foreignkey')
    op.create_foreign_key(None, 'clips', 'tracks', ['track_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clips', type_='foreignkey')
    op.create_foreign_key('clips_track_id_fkey', 'clips', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
