"""fix

Revision ID: 5ac1f835ebb9
Revises: e11e3e9c3c18
Create Date: 2023-01-28 18:28:01.875866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac1f835ebb9'
down_revision = 'e11e3e9c3c18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
