"""fix

Revision ID: 64c22a1903a9
Revises: 49766419e3c0
Create Date: 2022-10-27 14:01:51.126313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c22a1903a9'
down_revision = '49766419e3c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('public_profiles_links_picture_id_fkey', 'public_profiles_links', type_='foreignkey')
    op.create_foreign_key(None, 'public_profiles_links', 'files', ['picture_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('users_picture_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'files', ['picture_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_picture_id_fkey', 'users', 'files', ['picture_id'], ['id'])
    op.drop_constraint(None, 'public_profiles_links', type_='foreignkey')
    op.create_foreign_key('public_profiles_links_picture_id_fkey', 'public_profiles_links', 'files', ['picture_id'], ['id'])
    # ### end Alembic commands ###
