"""added albums table

Revision ID: 6e68ccdaf77d
Revises: 649399350f3a
Create Date: 2022-11-03 23:23:17.948432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e68ccdaf77d'
down_revision = '649399350f3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=38), nullable=False),
                    sa.Column('open_date', sa.DateTime(), nullable=False),
                    sa.Column('picture_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['artist_id'], ['public_profiles.id'], ),
                    sa.ForeignKeyConstraint(
                        ['picture_id'], ['files.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
