"""fix

Revision ID: 70629ef39399
Revises: 5ac1f835ebb9
Create Date: 2023-01-28 19:54:24.926723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70629ef39399'
down_revision = '5ac1f835ebb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_picture_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key('users_picture_id_fkey', 'users', 'images', ['picture_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_picture_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key('users_picture_id_fkey', 'users', 'images', ['picture_id'], ['id'])
    # ### end Alembic commands ###
