"""added track relationship to clip

Revision ID: 7143974f5941
Revises: 
Create Date: 2023-04-23 22:21:02.314873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7143974f5941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('track_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_clips_track_id'), 'clips', ['track_id'], unique=False)
    op.create_foreign_key(None, 'clips', 'tracks', ['track_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clips', type_='foreignkey')
    op.drop_index(op.f('ix_clips_track_id'), table_name='clips')
    op.drop_column('clips', 'track_id')
    # ### end Alembic commands ###
