"""updated favorite_tracks table

Revision ID: 75907183733f
Revises: 67f4267c5e10
Create Date: 2022-11-25 14:41:45.876290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75907183733f'
down_revision = '67f4267c5e10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
