"""added playlists tables

Revision ID: 75a4b84ebdbd
Revises: 994c786ec146
Create Date: 2023-02-22 00:30:56.460831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75a4b84ebdbd'
down_revision = '994c786ec146'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_name'), 'playlists', ['name'], unique=False)
    op.create_table('favorites_playlists',
    sa.Column('playlist_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'user_id')
    )
    op.create_table('playlists_tracks',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('playlist_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('track_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'track_id')
    )
    op.create_index(op.f('ix_playlists_tracks_playlist_id'), 'playlists_tracks', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlists_tracks_track_id'), 'playlists_tracks', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlists_tracks_track_id'), table_name='playlists_tracks')
    op.drop_index(op.f('ix_playlists_tracks_playlist_id'), table_name='playlists_tracks')
    op.drop_table('playlists_tracks')
    op.drop_table('favorites_playlists')
    op.drop_index(op.f('ix_playlists_name'), table_name='playlists')
    op.drop_table('playlists')
    # ### end Alembic commands ###
