"""added track index in album

Revision ID: 7ac86a4123f7
Revises: 39e6b852a44d
Create Date: 2022-11-17 12:26:42.716933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac86a4123f7'
down_revision = '39e6b852a44d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('track_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'track_position')
    # ### end Alembic commands ###
