"""reworked change role requests

Revision ID: 824407b06585
Revises: 
Create Date: 2023-02-04 23:45:05.125450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '824407b06585'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers_change_role_requests', sa.Column('setted_account_status', sa.Enum('musician', 'radiostaion', 'user', 'superuser', name='usertypeenum'), nullable=False))
    op.add_column('change_role_requests', sa.Column('request_status', sa.Enum('in_progress', 'accepted', 'rejected', name='changerolerequeststatus'), nullable=False))
    op.add_column('change_role_requests', sa.Column('requested_account_status', sa.Enum('musician', 'radiostaion', 'user', 'superuser', name='usertypeenum'), nullable=False))
    op.alter_column('change_role_requests', 'time_created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('change_role_requests', 'account_status')
    op.drop_column('change_role_requests', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_role_requests', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('change_role_requests', sa.Column('account_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('change_role_requests', 'time_created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('change_role_requests', 'requested_account_status')
    op.drop_column('change_role_requests', 'request_status')
    op.drop_column('answers_change_role_requests', 'setted_account_status')
    # ### end Alembic commands ###
