"""added musician relationship to clips table

Revision ID: 87cf03a659d9
Revises: 5c079e1f9b98
Create Date: 2022-11-27 01:20:01.600192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cf03a659d9'
down_revision = '5c079e1f9b98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('musician_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clips', 'public_profiles', ['musician_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clips', type_='foreignkey')
    op.drop_column('clips', 'musician_id')
    # ### end Alembic commands ###
