"""added it column

Revision ID: 8bfb5b3e6ccc
Revises: 7143974f5941
Create Date: 2023-04-27 23:41:49.572958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8bfb5b3e6ccc'
down_revision = '7143974f5941'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listen_album_history', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_listen_album_history_id'), 'listen_album_history', ['id'], unique=False)
    op.alter_column('listen_track_history', 'listen_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('listen_track_history_user_id_fkey', 'listen_track_history', type_='foreignkey')
    op.drop_constraint('listen_track_history_track_id_fkey', 'listen_track_history', type_='foreignkey')
    op.create_foreign_key(None, 'listen_track_history', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'listen_track_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listen_track_history', type_='foreignkey')
    op.drop_constraint(None, 'listen_track_history', type_='foreignkey')
    op.create_foreign_key('listen_track_history_track_id_fkey', 'listen_track_history', 'tracks', ['track_id'], ['id'])
    op.create_foreign_key('listen_track_history_user_id_fkey', 'listen_track_history', 'users', ['user_id'], ['id'])
    op.alter_column('listen_track_history', 'listen_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_listen_album_history_id'), table_name='listen_album_history')
    op.drop_column('listen_album_history', 'id')
    # ### end Alembic commands ###
