"""added playlist creation date

Revision ID: 8db37f4741a3
Revises: 75a4b84ebdbd
Create Date: 2023-02-23 14:05:49.284857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db37f4741a3'
down_revision = '75a4b84ebdbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'created_at')
    # ### end Alembic commands ###
