"""new table with images

Revision ID: 94c3d767ac69
Revises: 73bb5364ec89
Create Date: 2022-11-28 21:52:03.811163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c3d767ac69'
down_revision = '73bb5364ec89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
