"""added cascade deletion

Revision ID: 9591ff48a930
Revises: 73e60d8216b5
Create Date: 2023-01-28 17:38:42.999817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9591ff48a930'
down_revision = '73e60d8216b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_genres',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('album_id', 'genre_id')
    )
    op.drop_table('albums_genres_table')
    op.alter_column('change_role_requests_files', 'file_id',
               existing_type=postgresql.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('listen_track_history', sa.Column('listened', sa.Boolean(), nullable=False))
    op.drop_constraint('users_picture_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'images', ['picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_picture_id_fkey', 'users', 'images', ['picture_id'], ['id'], ondelete='SET NULL')
    op.drop_column('listen_track_history', 'listened')
    op.alter_column('change_role_requests_files', 'file_id',
               existing_type=sa.Integer(),
               type_=postgresql.UUID(),
               existing_nullable=False)
    op.create_table('albums_genres_table',
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name='albums_genres_table_album_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='albums_genres_table_genre_id_fkey'),
    sa.PrimaryKeyConstraint('album_id', 'genre_id', name='albums_genres_table_pkey')
    )
    op.drop_table('album_genres')
    # ### end Alembic commands ###
