"""added index=True to models

Revision ID: 994c786ec146
Revises: 651cb14b6bc9
Create Date: 2023-02-16 21:09:06.655169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994c786ec146'
down_revision = '651cb14b6bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clips_name'), 'clips', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clips_name'), table_name='clips')
    # ### end Alembic commands ###
