"""added accept requests

Revision ID: 9a8a235483ca
Revises: f15b65b3ad03
Create Date: 2022-10-16 15:15:27.706259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8a235483ca'
down_revision = 'f15b65b3ad03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers_change_role_requests', sa.Column('accept', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers_change_role_requests', 'accept')
    # ### end Alembic commands ###
