"""added extention column in files table

Revision ID: 9bb3fd9a20df
Revises: 2e9f7155d847
Create Date: 2022-11-28 22:39:01.259138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb3fd9a20df'
down_revision = '2e9f7155d847'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('ext', sa.String(), nullable=False))
    op.alter_column('files', 'original_file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'original_file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('files', 'ext')
    # ### end Alembic commands ###
