"""upd

Revision ID: ae7074b66d2c
Revises: 8a5d8012cb7f
Create Date: 2022-10-14 12:17:13.027632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7074b66d2c'
down_revision = '8a5d8012cb7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_role_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('files_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_role_requests_id'), 'change_role_requests', ['id'], unique=False)
    op.add_column('files', sa.Column('original_file_name', sa.String(), nullable=True))
    op.add_column('files', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'type')
    op.drop_column('files', 'original_file_name')
    op.drop_index(op.f('ix_change_role_requests_id'), table_name='change_role_requests')
    op.drop_table('change_role_requests')
    # ### end Alembic commands ###
