"""added uploaded column in albums table

Revision ID: af20dd494a89
Revises: 56a3a5826855
Create Date: 2022-11-29 00:04:25.130115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af20dd494a89'
down_revision = '56a3a5826855'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('uploaded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'uploaded')
    # ### end Alembic commands ###
