"""many to many tracks genres

Revision ID: afdd93fb842d
Revises: 274c5566ac28
Create Date: 2022-11-09 13:54:29.701828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdd93fb842d'
down_revision = '274c5566ac28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks_genres_table',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('track_id', 'genre_id')
    )
    op.drop_constraint('tracks_genre_id_fkey', 'tracks', type_='foreignkey')
    op.drop_column('tracks', 'genre_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tracks_genre_id_fkey', 'tracks', 'genres', ['genre_id'], ['id'])
    op.drop_table('tracks_genres_table')
    # ### end Alembic commands ###
