"""renamed extension column

Revision ID: bec6d38e7b64
Revises: 9bb3fd9a20df
Create Date: 2022-11-28 22:41:50.233298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec6d38e7b64'
down_revision = '9bb3fd9a20df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('extension', sa.String(), nullable=False))
    op.drop_column('files', 'ext')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('files', 'extension')
    # ### end Alembic commands ###
