"""rename columns

Revision ID: c459d4dc4810
Revises: 12a2132c82c4
Create Date: 2022-11-05 21:15:07.008019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c459d4dc4810'
down_revision = '12a2132c82c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('musician_id', sa.Integer(), nullable=False))
    op.drop_constraint('albums_artist_id_fkey', 'albums', type_='foreignkey')
    op.create_foreign_key(None, 'albums', 'public_profiles', ['musician_id'], ['id'])
    op.drop_column('albums', 'artist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.create_foreign_key('albums_artist_id_fkey', 'albums', 'public_profiles', ['artist_id'], ['id'])
    op.drop_column('albums', 'musician_id')
    # ### end Alembic commands ###
