"""added date 

Revision ID: c85fb88dc441
Revises: 8bfb5b3e6ccc
Create Date: 2023-04-28 19:29:42.681091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85fb88dc441'
down_revision = '8bfb5b3e6ccc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_albums', sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_albums', 'date')
    # ### end Alembic commands ###
