"""updated slider table

Revision ID: d16ad8e1868f
Revises: 
Create Date: 2023-03-16 10:41:23.085056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd16ad8e1868f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('picture_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('slides', sa.Column('url', sa.String(), nullable=True))
    op.drop_constraint('slides_image_id_fkey', 'slides', type_='foreignkey')
    op.create_foreign_key(None, 'slides', 'images', ['picture_id'], ['id'])
    op.drop_column('slides', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('image_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'slides', type_='foreignkey')
    op.create_foreign_key('slides_image_id_fkey', 'slides', 'images', ['image_id'], ['id'])
    op.drop_column('slides', 'url')
    op.drop_column('slides', 'picture_id')
    # ### end Alembic commands ###
