"""add public profile tables

Revision ID: dfb2695d0de7
Revises: 9a8a235483ca
Create Date: 2022-10-26 10:36:53.558508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb2695d0de7'
down_revision = '9a8a235483ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_profiles_id'), 'public_profiles', ['id'], unique=False)
    op.create_table('public_profiles_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_profile_id', sa.Integer(), nullable=True),
    sa.Column('telegram', sa.String(length=32), nullable=True),
    sa.Column('youtube', sa.String(length=32), nullable=True),
    sa.Column('vk', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['public_profile_id'], ['public_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_profiles_links_id'), 'public_profiles_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_profiles_links_id'), table_name='public_profiles_links')
    op.drop_table('public_profiles_links')
    op.drop_index(op.f('ix_public_profiles_id'), table_name='public_profiles')
    op.drop_table('public_profiles')
    # ### end Alembic commands ###
