"""added track index in album

Revision ID: e1fd4b1343d3
Revises: 7ac86a4123f7
Create Date: 2022-11-17 12:27:01.482901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fd4b1343d3'
down_revision = '7ac86a4123f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('track_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'track_position')
    # ### end Alembic commands ###
