"""added cascade delete

Revision ID: ef0245637bc0
Revises: a7bc7d70234b
Create Date: 2023-05-06 15:20:05.060045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0245637bc0'
down_revision = 'a7bc7d70234b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clips_track_id_fkey', 'clips', type_='foreignkey')
    op.create_foreign_key(None, 'clips', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clips', type_='foreignkey')
    op.create_foreign_key('clips_track_id_fkey', 'clips', 'tracks', ['track_id'], ['id'])
    # ### end Alembic commands ###
