"""added grenres column

Revision ID: f84619e22f11
Revises: e234df00b05f
Create Date: 2022-11-08 00:31:01.935803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84619e22f11'
down_revision = 'e234df00b05f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
