"""e

Revision ID: 36458c242bdb
Revises: 7a97c32ac22b
Create Date: 2022-10-08 20:02:00.682087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36458c242bdb'
down_revision = '7a97c32ac22b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
