"""FIX

Revision ID: 3f195e3c14df
Revises: 6da4e0d907a1
Create Date: 2022-10-10 20:31:11.044160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f195e3c14df'
down_revision = '6da4e0d907a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
