"""initial

Revision ID: 40460e5470e6
Revises: f92aaf9a7810
Create Date: 2022-09-23 23:44:28.016061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40460e5470e6'
down_revision = 'f92aaf9a7810'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
