"""e

Revision ID: 7a97c32ac22b
Revises: f7cf87c814e7
Create Date: 2022-10-08 20:00:05.066342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a97c32ac22b'
down_revision = 'f7cf87c814e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
