"""d

Revision ID: 7ad84d1f9615
Revises: dae6ae1709d7
Create Date: 2022-10-07 21:29:52.330797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad84d1f9615'
down_revision = 'dae6ae1709d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_picture_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'picture_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_picture_id_fkey', 'users', 'files', ['picture_id'], ['id'])
    # ### end Alembic commands ###
