"""added foreign key for picture relationship fix 2

Revision ID: 94cb64f7e12f
Revises: aa1c02da5791
Create Date: 2022-10-08 19:54:38.594383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cb64f7e12f'
down_revision = 'aa1c02da5791'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
