"""init

Revision ID: a495e8cceb88
Revises: 2687c265e8d3
Create Date: 2022-09-23 23:25:00.164957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a495e8cceb88'
down_revision = '2687c265e8d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
