"""added foreign key for picture relationship

Revision ID: aa1c02da5791
Revises: b1b30d17edff
Create Date: 2022-10-08 19:48:24.480757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1c02da5791'
down_revision = 'b1b30d17edff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'files', ['picture_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'picture_id')
    # ### end Alembic commands ###
