"""c

Revision ID: dae6ae1709d7
Revises: bcdabf43da67
Create Date: 2022-10-07 21:09:08.282521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae6ae1709d7'
down_revision = 'bcdabf43da67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_picture_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'files', ['picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_picture_id_fkey', 'users', 'users', ['picture_id'], ['id'])
    # ### end Alembic commands ###
