"""empty message

Revision ID: e6f5e4aab0c9
Revises: 5995e5b38598
Create Date: 2022-09-24 19:19:37.480468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f5e4aab0c9'
down_revision = '5995e5b38598'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=256), nullable=True))
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
