"""added answers_change_role_requests table

Revision ID: f0018b253f80
Revises: b6f5d684793e
Create Date: 2022-10-15 13:33:12.642895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0018b253f80'
down_revision = 'b6f5d684793e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers_change_role_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['change_role_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_change_role_requests_id'), 'answers_change_role_requests', ['id'], unique=False)
    op.add_column('change_role_requests', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_role_requests', 'time_created')
    op.drop_index(op.f('ix_answers_change_role_requests_id'), table_name='answers_change_role_requests')
    op.drop_table('answers_change_role_requests')
    # ### end Alembic commands ###
