"""fix

Revision ID: f15b65b3ad03
Revises: dcd0a0fbd7ec
Create Date: 2022-10-16 14:33:24.971940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15b65b3ad03'
down_revision = 'dcd0a0fbd7ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_role_requests', sa.Column('account_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_role_requests', 'account_status')
    # ### end Alembic commands ###
