"""e

Revision ID: f7cf87c814e7
Revises: 94cb64f7e12f
Create Date: 2022-10-08 19:58:13.138899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cf87c814e7'
down_revision = '94cb64f7e12f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_picture_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'picture_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_picture_id_fkey', 'users', 'files', ['picture_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
